export const MQTT_STATE_CONNECTING = 'MQTT_STATE_CONNECTING'
export const MQTT_STATE_CONNECTED = 'MQTT_STATE_CONNECTED'
export const MQTT_STATE_OFFLINE = 'MQTT_STATE_OFFLINE'
export const MQTT_STATE_ERROR = 'MQTT_STATE_ERROR'
