export const MQTT_STATE_CONNECTING = 'MQTT_STATE_CONNECTING'
export const MQTT_STATE_CONNECTED = 'MQTT_STATE_CONNECTED'
export const MQTT_STATE_OFFLINE = 'MQTT_STATE_OFFLINE'
export const MQTT_STATE_ERROR = 'MQTT_STATE_ERROR'

export const CLIENT_LIST_VIEW_TYPE_TABLE = 'CLIENT_LIST_VIEW_TYPE_TABLE'
export const CLIENT_LIST_VIEW_TYPE_LIST = 'CLIENT_LIST_VIEW_TYPE_LIST'
