stages:
  - package
  - deploy

npm-build:
  image: node:6-alpine
  stage: package
  script:
    - npm install
    - npm run build

# deploy:
#   image: python:2.7
#   stage: deploy
#   only:
#   - master
#   script:
#     - "curl -s -X POST -H \"Authorization: Bearer: $DEPLOY_API_TOKEN\" https://api.metachris.com/tasks/deploy-python-boilerplate-frontend > response.txt"
#     - "cat response.txt"
#     - "grep msg response.txt"
#   environment:
#     name: production
